apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skillbox.fullname" . }}
  labels:
    {{- include "skillbox.labels" . | nindent 4 }}
type: Opaque
stringData:
  SKILLBOX_DB_DSN: {{ .Values.postgresql.dsn | quote }}
  SKILLBOX_S3_ACCESS_KEY: {{ .Values.minio.accessKey | quote }}
  SKILLBOX_S3_SECRET_KEY: {{ .Values.minio.secretKey | quote }}
  {{- if and .Values.redis.enabled .Values.redis.url }}
  SKILLBOX_REDIS_URL: {{ .Values.redis.url | quote }}
  {{- end }}
