apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: sandbox-dev

replicas:
  - name: skillbox-api
    count: 1

images:
  - name: ghcr.io/devs-group/skillbox
    newTag: dev-latest

configMapGenerator:
  - name: skillbox-config
    behavior: merge
    literals:
      - SKILLBOX_LOG_LEVEL=debug

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: skillbox-api
      spec:
        template:
          spec:
            containers:
              - name: api
                resources:
                  requests:
                    cpu: 50m
                    memory: 64Mi
                  limits:
                    cpu: 500m
                    memory: 256Mi
